# Generated by Django 5.0.2 on 2025-05-21 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LabOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.PositiveIntegerField(help_text='ID bệnh nhân từ User Service')),
                ('patient_name', models.CharField(help_text='Tên bệnh nhân', max_length=200)),
                ('doctor_id', models.PositiveIntegerField(help_text='ID bác sĩ từ User Service')),
                ('doctor_name', models.CharField(help_text='Tên bác sĩ', max_length=200)),
                ('ehr_encounter_id', models.CharField(blank=True, help_text='ID của encounter từ EHR Service (nếu có)', max_length=100, null=True)),
                ('order_date', models.DateTimeField(auto_now_add=True, help_text='Ngày tạo phiếu')),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('SAMPLE_COLLECTED', 'Sample Collected'), ('PROCESSING', 'Processing'), ('RESULTS_PENDING_REVIEW', 'Results Pending Review'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='REQUESTED', help_text='Trạng thái phiếu', max_length=50)),
                ('priority', models.CharField(choices=[('ROUTINE', 'Routine'), ('URGENT', 'Urgent')], default='ROUTINE', help_text='Mức độ ưu tiên', max_length=20)),
                ('notes_for_lab', models.TextField(blank=True, help_text='Ghi chú cho phòng xét nghiệm')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lab Order',
                'verbose_name_plural': 'Lab Orders',
            },
        ),
        migrations.CreateModel(
            name='TestCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_code', models.CharField(help_text='Mã xét nghiệm', max_length=20, unique=True)),
                ('test_name', models.CharField(help_text='Tên xét nghiệm', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Mô tả xét nghiệm')),
                ('sample_type_required', models.CharField(help_text='Loại mẫu cần thu thập', max_length=100)),
                ('turn_around_time_hours', models.PositiveIntegerField(default=24, help_text='Thời gian hoàn thành (giờ)')),
                ('price', models.DecimalField(decimal_places=2, help_text='Giá xét nghiệm', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Test Catalog',
                'verbose_name_plural': 'Test Catalog',
            },
        ),
        migrations.CreateModel(
            name='LabOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_id', models.CharField(blank=True, help_text='ID mẫu xét nghiệm', max_length=50, null=True)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('SAMPLE_COLLECTED', 'Sample Collected'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='REQUESTED', help_text='Trạng thái xét nghiệm', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lab_order', models.ForeignKey(help_text='Phiếu yêu cầu', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='laboratory.laborder')),
                ('test', models.ForeignKey(help_text='Xét nghiệm', on_delete=django.db.models.deletion.PROTECT, to='laboratory.testcatalog')),
            ],
            options={
                'verbose_name': 'Lab Order Item',
                'verbose_name_plural': 'Lab Order Items',
            },
        ),
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technician_id', models.PositiveIntegerField(help_text='ID kỹ thuật viên từ User Service')),
                ('technician_name', models.CharField(help_text='Tên kỹ thuật viên', max_length=200)),
                ('result_date', models.DateTimeField(auto_now_add=True, help_text='Ngày có kết quả')),
                ('verified_by_id', models.PositiveIntegerField(blank=True, help_text='ID người xác nhận từ User Service', null=True)),
                ('verified_by_name', models.CharField(blank=True, help_text='Tên người xác nhận', max_length=200, null=True)),
                ('verification_date', models.DateTimeField(blank=True, help_text='Ngày xác nhận', null=True)),
                ('result_data', models.JSONField(default=dict, help_text='Dữ liệu kết quả dạng JSON')),
                ('interpretation', models.TextField(blank=True, help_text='Diễn giải kết quả')),
                ('is_abnormal', models.BooleanField(default=False, help_text='Kết quả bất thường')),
                ('result_file_url', models.URLField(blank=True, help_text='URL file kết quả (nếu có)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lab_order_item', models.OneToOneField(help_text='Xét nghiệm', on_delete=django.db.models.deletion.CASCADE, related_name='result', to='laboratory.laborderitem')),
            ],
            options={
                'verbose_name': 'Lab Result',
                'verbose_name_plural': 'Lab Results',
            },
        ),
        migrations.CreateModel(
            name='TestNormalRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_name', models.CharField(help_text='Tên chỉ số', max_length=100)),
                ('unit', models.CharField(help_text='Đơn vị đo', max_length=20)),
                ('min_value_male', models.DecimalField(blank=True, decimal_places=2, help_text='Giá trị tối thiểu cho nam', max_digits=10, null=True)),
                ('max_value_male', models.DecimalField(blank=True, decimal_places=2, help_text='Giá trị tối đa cho nam', max_digits=10, null=True)),
                ('min_value_female', models.DecimalField(blank=True, decimal_places=2, help_text='Giá trị tối thiểu cho nữ', max_digits=10, null=True)),
                ('max_value_female', models.DecimalField(blank=True, decimal_places=2, help_text='Giá trị tối đa cho nữ', max_digits=10, null=True)),
                ('min_value', models.DecimalField(blank=True, decimal_places=2, help_text='Giá trị tối thiểu chung', max_digits=10, null=True)),
                ('max_value', models.DecimalField(blank=True, decimal_places=2, help_text='Giá trị tối đa chung', max_digits=10, null=True)),
                ('description', models.TextField(blank=True, help_text='Mô tả bổ sung')),
                ('test', models.ForeignKey(help_text='Xét nghiệm', on_delete=django.db.models.deletion.CASCADE, related_name='normal_ranges', to='laboratory.testcatalog')),
            ],
            options={
                'verbose_name': 'Test Normal Range',
                'verbose_name_plural': 'Test Normal Ranges',
                'unique_together': {('test', 'parameter_name')},
            },
        ),
    ]
