# Generated by Django 5.1.6 on 2025-05-21 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField(help_text='ID from User Service', verbose_name='Patient ID')),
                ('doctor_id', models.IntegerField(help_text='ID from User Service', verbose_name='Doctor ID')),
                ('appointment_time', models.DateTimeField(verbose_name='Appointment Time')),
                ('duration_minutes', models.IntegerField(default=30, verbose_name='Duration (minutes)')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED_PATIENT', 'Cancelled by Patient'), ('CANCELLED_DOCTOR', 'Cancelled by Doctor'), ('COMPLETED', 'Completed'), ('NO_SHOW', 'No Show')], default='PENDING', max_length=20, verbose_name='Status')),
                ('reason_for_visit', models.TextField(blank=True, verbose_name='Reason for Visit')),
                ('notes_doctor', models.TextField(blank=True, verbose_name='Doctor Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
                'indexes': [models.Index(fields=['patient_id'], name='appointment_patient_94a7ef_idx'), models.Index(fields=['doctor_id'], name='appointment_doctor__649ad1_idx'), models.Index(fields=['appointment_time'], name='appointment_appoint_b9e7fe_idx'), models.Index(fields=['status'], name='appointment_status_8fe9d7_idx')],
            },
        ),
        migrations.CreateModel(
            name='DoctorSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_id', models.IntegerField(help_text='ID from User Service', verbose_name='Doctor ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], verbose_name='Day of Week')),
                ('start_time', models.TimeField(verbose_name='Start Time')),
                ('end_time', models.TimeField(verbose_name='End Time')),
                ('is_available', models.BooleanField(default=True, verbose_name='Is Available')),
                ('valid_from', models.DateField(verbose_name='Valid From')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name='Valid To')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Doctor Schedule',
                'verbose_name_plural': 'Doctor Schedules',
                'indexes': [models.Index(fields=['doctor_id'], name='appointment_doctor__df5211_idx'), models.Index(fields=['day_of_week'], name='appointment_day_of__93c2bc_idx'), models.Index(fields=['valid_from', 'valid_to'], name='appointment_valid_f_989cde_idx')],
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_id', models.IntegerField(help_text='ID from User Service', verbose_name='Doctor ID')),
                ('start_time', models.DateTimeField(verbose_name='Start Time')),
                ('end_time', models.DateTimeField(verbose_name='End Time')),
                ('is_booked', models.BooleanField(default=False, verbose_name='Is Booked')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Time Slot',
                'verbose_name_plural': 'Time Slots',
                'indexes': [models.Index(fields=['doctor_id'], name='appointment_doctor__3b2323_idx'), models.Index(fields=['start_time', 'end_time'], name='appointment_start_t_fd2bd6_idx'), models.Index(fields=['is_booked'], name='appointment_is_book_b299db_idx')],
            },
        ),
    ]
