# Generated by Django 5.2.1 on 2025-05-21 16:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_code', models.CharField(help_text='Mã thuốc', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Tên thuốc', max_length=255)),
                ('generic_name', models.CharField(blank=True, help_text='Tên generic', max_length=255)),
                ('manufacturer', models.CharField(blank=True, help_text='Nhà sản xuất', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Mô tả thuốc')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Giá tham khảo', max_digits=10)),
                ('dosage_form', models.CharField(help_text='Dạng bào chế (viên, ống, v.v.)', max_length=100)),
                ('strength', models.CharField(help_text='Nồng độ/Hàm lượng', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Medication',
                'verbose_name_plural': 'Medications',
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.PositiveIntegerField(help_text='ID bệnh nhân từ User Service')),
                ('patient_name', models.CharField(help_text='Tên bệnh nhân', max_length=255)),
                ('doctor_id', models.PositiveIntegerField(help_text='ID bác sĩ từ User Service')),
                ('doctor_name', models.CharField(help_text='Tên bác sĩ', max_length=255)),
                ('ehr_encounter_id', models.CharField(blank=True, help_text='ID của encounter từ EHR Service (nếu có)', max_length=100, null=True)),
                ('date_prescribed', models.DateTimeField(default=django.utils.timezone.now, help_text='Ngày kê đơn')),
                ('status', models.CharField(choices=[('PENDING_VERIFICATION', 'Pending Verification'), ('VERIFIED', 'Verified'), ('DISPENSED_PARTIAL', 'Dispensed Partial'), ('DISPENSED_FULL', 'Dispensed Full'), ('CANCELLED', 'Cancelled')], default='PENDING_VERIFICATION', help_text='Trạng thái đơn thuốc', max_length=50)),
                ('notes_for_pharmacist', models.TextField(blank=True, help_text='Ghi chú cho dược sĩ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Prescription',
                'verbose_name_plural': 'Prescriptions',
            },
        ),
        migrations.CreateModel(
            name='PharmacyStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_on_hand', models.PositiveIntegerField(default=0, help_text='Số lượng hiện có')),
                ('reorder_level', models.PositiveIntegerField(default=10, help_text='Mức cần đặt lại')),
                ('last_stocked_date', models.DateTimeField(blank=True, help_text='Ngày nhập kho gần nhất', null=True)),
                ('medication', models.OneToOneField(help_text='Thuốc', on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='pharmacy.medication')),
            ],
            options={
                'verbose_name': 'Pharmacy Stock',
                'verbose_name_plural': 'Pharmacy Stocks',
            },
        ),
        migrations.CreateModel(
            name='BatchExpiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(help_text='Số lô', max_length=100)),
                ('quantity', models.PositiveIntegerField(help_text='Số lượng trong lô')),
                ('expiry_date', models.DateField(help_text='Ngày hết hạn')),
                ('pharmacy_stock', models.ForeignKey(help_text='Kho thuốc', on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='pharmacy.pharmacystock')),
            ],
            options={
                'verbose_name': 'Batch Expiry',
                'verbose_name_plural': 'Batch Expiries',
            },
        ),
        migrations.CreateModel(
            name='DispenseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pharmacist_id', models.PositiveIntegerField(help_text='ID dược sĩ từ User Service')),
                ('pharmacist_name', models.CharField(help_text='Tên dược sĩ', max_length=255)),
                ('date_dispensed', models.DateTimeField(default=django.utils.timezone.now, help_text='Ngày cấp phát')),
                ('payment_status', models.CharField(choices=[('PAID', 'Paid'), ('PENDING_BILLING', 'Pending Billing')], default='PENDING_BILLING', help_text='Trạng thái thanh toán', max_length=50)),
                ('notes', models.TextField(blank=True, help_text='Ghi chú')),
                ('prescription', models.ForeignKey(help_text='Đơn thuốc', on_delete=django.db.models.deletion.CASCADE, related_name='dispense_logs', to='pharmacy.prescription')),
            ],
            options={
                'verbose_name': 'Dispense Log',
                'verbose_name_plural': 'Dispense Logs',
            },
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage', models.CharField(help_text='Liều dùng (ví dụ: 1 viên)', max_length=100)),
                ('frequency', models.CharField(help_text='Tần suất (ví dụ: 3 lần/ngày)', max_length=100)),
                ('duration_days', models.PositiveIntegerField(help_text='Thời gian dùng (ngày)')),
                ('instructions', models.TextField(blank=True, help_text='Hướng dẫn sử dụng')),
                ('quantity_prescribed', models.PositiveIntegerField(help_text='Số lượng kê đơn')),
                ('quantity_dispensed', models.PositiveIntegerField(default=0, help_text='Số lượng đã cấp phát')),
                ('medication', models.ForeignKey(help_text='Thuốc', on_delete=django.db.models.deletion.PROTECT, to='pharmacy.medication')),
                ('prescription', models.ForeignKey(help_text='Đơn thuốc', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pharmacy.prescription')),
            ],
            options={
                'verbose_name': 'Prescription Item',
                'verbose_name_plural': 'Prescription Items',
            },
        ),
        migrations.CreateModel(
            name='DispenseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_dispensed', models.PositiveIntegerField(help_text='Số lượng cấp phát')),
                ('batch_number', models.CharField(blank=True, help_text='Số lô thuốc cấp phát', max_length=100, null=True)),
                ('dispense_log', models.ForeignKey(help_text='Nhật ký cấp phát', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pharmacy.dispenselog')),
                ('medication', models.ForeignKey(help_text='Thuốc', on_delete=django.db.models.deletion.PROTECT, to='pharmacy.medication')),
                ('prescription_item', models.ForeignKey(help_text='Chi tiết đơn thuốc', on_delete=django.db.models.deletion.CASCADE, related_name='dispense_items', to='pharmacy.prescriptionitem')),
            ],
            options={
                'verbose_name': 'Dispense Item',
                'verbose_name_plural': 'Dispense Items',
            },
        ),
    ]
