# Generated by Django 5.1.6 on 2025-05-21 18:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InsurancePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField(help_text='ID of the patient from User Service')),
                ('insurance_provider_id', models.IntegerField(blank=True, help_text='ID of insurance provider from User Service', null=True)),
                ('provider_name', models.CharField(max_length=100)),
                ('policy_number', models.CharField(max_length=100, unique=True)),
                ('member_id', models.CharField(max_length=100)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField()),
                ('coverage_details_json', models.JSONField(blank=True, default=dict, help_text='Insurance coverage details')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField(help_text='ID of the patient from User Service')),
                ('invoice_number', models.CharField(help_text='Unique invoice number', max_length=50, unique=True)),
                ('issue_date', models.DateField(default=django.utils.timezone.now, help_text='Date invoice was issued')),
                ('due_date', models.DateField(help_text='Date payment is due')),
                ('sub_total_amount', models.DecimalField(decimal_places=2, help_text='Subtotal amount before tax/discount', max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, help_text='Tax amount', max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, help_text='Discount amount', max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total amount after tax and discount', max_digits=10)),
                ('amount_paid_by_patient', models.DecimalField(decimal_places=2, default=0, help_text='Amount paid by patient', max_digits=10)),
                ('amount_paid_by_insurance', models.DecimalField(decimal_places=2, default=0, help_text='Amount paid by insurance', max_digits=10)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_PATIENT', 'Pending Patient Payment'), ('PENDING_INSURANCE', 'Pending Insurance Payment'), ('PARTIALLY_PAID', 'Partially Paid'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue'), ('CANCELLED', 'Cancelled'), ('WRITTEN_OFF', 'Written Off')], default='DRAFT', help_text='Current status of invoice', max_length=20)),
                ('related_appointment_id', models.IntegerField(blank=True, help_text='ID of related appointment, if any', null=True)),
                ('related_prescription_dispense_id', models.CharField(blank=True, help_text='ID of related prescription dispense, if any', max_length=50, null=True)),
                ('related_lab_order_id', models.CharField(blank=True, help_text='ID of related lab order, if any', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='InsuranceClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_date', models.DateField(default=django.utils.timezone.now)),
                ('claim_amount', models.DecimalField(decimal_places=2, help_text='Amount claimed from insurance', max_digits=10)),
                ('approved_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rejected_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('PROCESSING', 'Processing'), ('AWAITING_DOCUMENTS', 'Awaiting Documents'), ('APPROVED', 'Approved'), ('PARTIALLY_APPROVED', 'Partially Approved'), ('REJECTED', 'Rejected'), ('PAID_BY_INSURER', 'Paid by Insurer'), ('CLOSED', 'Closed')], default='SUBMITTED', max_length=30)),
                ('insurer_notes', models.TextField(blank=True, help_text='Notes from insurance provider')),
                ('hospital_notes', models.TextField(blank=True, help_text='Notes from hospital staff')),
                ('claim_reference_number', models.CharField(blank=True, help_text='External reference number', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('insurance_policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='billing_insurance.insurancepolicy')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='billing_insurance.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('CONSULTATION', 'Consultation'), ('MEDICATION', 'Medication'), ('LAB_TEST', 'Laboratory Test'), ('OTHER_SERVICE', 'Other Service')], max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=8)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, help_text='quantity * unit_price', max_digits=10)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='billing_insurance.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField(help_text='ID of the patient from User Service')),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('CREDIT_CARD', 'Credit Card'), ('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer'), ('INSURANCE_PAYOUT', 'Insurance Payout'), ('VOUCHER', 'Voucher')], max_length=50)),
                ('transaction_id', models.CharField(blank=True, help_text='External transaction ID', max_length=100, null=True)),
                ('status', models.CharField(choices=[('SUCCESS', 'Successful'), ('FAILED', 'Failed'), ('PENDING', 'Pending'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='billing_insurance.invoice')),
            ],
        ),
    ]
